version: '3'
services:

  api:
    build: .
    ports:
      - "3000:3000"

  postgres:
    image: "postgres:16.2"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "financial-control-db"

